export const names = [
  "Abigail",
  "Ada",
  "Adele",
  "Adriana",
  "Alaina",
  "Alana",
  "Alexa",
  "Alexandra",
  "Alexis",
  "unisex name",
  "Alice",
  "Alina",
  "Latin origin",
  "Aliyah",
  "Alison",
  "Alyssa",
  "Register here to claim",
  "Amara",
  "Amaya",
  "Amber",
  "Amelia",
  "Amelie",
  "Amiyah",
  "Amy",
  "Ana",
  "Anastasia",
  "Greek origin",
  "Andrea",
  "Angela",
  "Angelina",
  "Anna",
  "Annabelle",
  "Arabella",
  "Aria",
  "Ariana",
  "Welsh origin",
  "Arianna",
  "Ariel",
  "Arya",
  "Ashley",
  "English origin",
  "Aspen",
  "Athena",
  "Aubree",
  "Aubrey",
  "Audrey",
  "Aurora",
  "Autumn",
  "Ava",
  "Avery",
  "Ayla",
  "Bailey",
  "Bella",
  "Blake",
  "English origin",
  "Bonnie",
  "Brianna",
  "Brielle",
  "Brooke",
  "German origin",
  "Brooklyn",
  "Callie",
  "Camila",
  "Camille",
  "Caroline",
  "Catalina",
  "Charlie",
  "Charlotte",
  "Chloe",
  "Claire",
  "Clara",
  "Cora",
  "Daisy",
  "Dakota",
  "Daniela",
  "Darcie",
  "Delaney",
  "Delilah",
  "Destiny",
  "Diana",
  "Eden",
  "French origin",
  "Eleanor",
  "Elena",
  "Eliana",
  "Elise",
  "Eliza",
  "Elizabeth",
  "Ella",
  "Ellie",
  "Eloise",
  "Elsie",
  "Elspeth",
  "Ember",
  "Emery",
  "Emilia",
  "Emily",
  "Emma",
  "Erin",
  "Next step",
  "back",
  "Continue",
  "back",
  "Find address",
  "Enter Address Manually",
  "Enter Address Manually",
  "Next step",
  "back",
  "View our trusted partners",
  "Manage trusted partners",
  "Esme",
  "Esther",
  "Eva",
  "Evangeline",
  "Evelyn",
  "Evie",
  "Faith",
  "English origin",
  "Fatima",
  "Felicia",
  "Fiona",
  "Florence",
  "Latin origin",
  "Freya",
  "Gabrielle",
  "Gemma",
  "Genesis",
  "Genevieve",
  "Georgia",
  "Gianna",
  "Grace",
  "Gracie",
  "Hadley",
  "Hailey",
  "Hallie",
  "Hannah",
  "Harley",
  "Harmony",
  "Harper",
  "Harriet",
  "Hazel",
  "Heather",
  "Heidi",
  "Holly",
  "Hope",
  "Imogen",
  "Celtic origin",
  "Iris",
  "Isabel",
  "Isabella",
  "Isla",
  "Ivy",
  "Jade",
  "Jane",
  "Jasmine",
  "Jayla",
  "Jessica",
  "Jacqueline",
  "Joanna",
  "Jocelyn",
  "Josephine",
  "Josie",
  "Julia",
  "Julianna",
  "Julie",
  "Juliet",
  "June",
  "Juniper",
  "Kamila",
  "Kate",
  "Katherine",
  "Kayla",
  "Kaylee",
  "Keisha",
  "Kennedy",
  "Kiara",
  "Kimberly",
  "Kylie",
  "Kyra",
  "Laila",
  "Lara",
  "Lauren",
  "Layla",
  "Leah",
  "Leia",
  "Leila",
  "Leilani",
  "Lia",
  "Lila",
  "Lillian",
  "Lily",
  "Lola",
  "Spanish name",
  "London",
  "Lottie",
  "Lucia",
  "Lucille",
  "Lucy",
  "Luna",
  "Lydia",
  "Lyla",
  "Mackenzie",
  "Madeline",
  "Madelyn",
  "Madison",
  "Maisie",
  "Makayla",
  "Malia",
  "Margaret",
  "Maria",
  "Mariah",
  "Mariana",
  "Marley",
  "Martha",
  "Mary",
  "Maryam",
  "Matilda",
  "German origin",
  "Maya",
  "Greek origin",
  "Mckenna",
  "Mckenzie",
  "Scottish origin",
  "Melanie",
  "Melissa",
  "Melody",
  "Mia",
  "Michelle",
  "Mila",
  "Millie",
  "Molly",
  "Morgan",
  "Mya",
  "Myla",
  "Nancy",
  "Naomi",
  "Natalia",
  "Natalie",
  "Nevaeh",
  "Nicole",
  "Noelle",
  "Nora",
  "Nova",
  "Nur",
  "Olive",
  "Olivia",
  "Orla",
  "Paige",
  "Paisley",
  "Parker",
  "Payton",
  "Penelope",
  "Greek origin",
  "Penny",
  "Peyton",
  "Phoebe",
  "Piper",
  "Poppy",
  "Presley",
  "Rachel",
  "Raegan",
  "Reagan",
  "Rebecca",
  "Reese",
  "French origins",
  "Riley",
  "River",
  "Robin",
  "English origin",
  "Rosalie",
  "Rose",
  "Rosie",
  "Rowan",
  "Ruby",
  "Ruth",
  "Rylee",
  "Ryleigh",
  "Sabrina",
  "Sadie",
  "Sally",
  "Samantha",
  "Samara",
  "Sara",
  "Sarah",
  "Savannah",
  "Sawyer",
  "Scarlett",
  "Selena",
  "Serenity",
  "Sienna",
  "Skylar",
  "Sloane",
  "Sofia",
  "Greek origin",
  "Sophia",
  "Sophie",
  "Stella",
  "Latin origin",
  "Summer",
  "Sydney",
  "Taylor",
  "Teagan",
  "Tessa",
  "Thea",
  "Trinity",
  "Valentina",
  "Valeria",
  "Valerie",
  "Vanessa",
  "Vera",
  "Russian",
  "Victoria",
  "Violet",
  "Vivian",
  "Vivienne",
  "Willow",
];

export const audioUrls = [
  "https://static.canva.com/preso/music/Energetic%20Burst_v01.mp3",
  "https://static.canva.com/preso/music/Upbeat%20Fun_v01.mp3",
  "https://static.canva.com/preso/music/Focus%20Time_v01.mp3",
  "https://static.canva.com/preso/music/Theatrical%20Gain_v01.mp3",
  "https://static.canva.com/preso/music/Focus_Time_LoFi_v02.mp3",
];

export const details = {
  name: "Aditya Prasad",
  exp: "3",
  img: "https://avatars.githubusercontent.com/u/44614594?s=400&u=92fa4155c955fe485545f01bff48a10dafc04303&v=4",
  skills: [
    "Next JS",
    "React JS",
    "Angular",
    "JavaScript",
    "D3.js",
    "P5.js",
    "Node JS",
    "GraphQL",
    "Linux",
    "Ubuntu Server",
    "Nginx",
    "HTML5 & CSS3",
    "Tailwind CSS",
  ],
  social: {
    GITURL: "https://github.com/adityaprasad48",
    LinkDinURL: "https://www.linkedin.com/in/aditya-prasad-26b2b2183/",
  },
};

export const songs = [
  {
    id: 1,
    title: "Rainy Day In Town With Birds Singing",
    src: "https://cdn.pixabay.com/audio/2024/03/21/audio_b20bc53f05.mp3",
  },
  // {
  //   id: 2,
  //   title: "Soft Rain Ambient",
  //   src: "https://cdn.pixabay.com/audio/2021/08/09/audio_e25ff0623a.mp3",
  // },
  {
    id: 3,
    title: "Forest with small river birds and nature field recording",
    src: "https://cdn.pixabay.com/audio/2021/08/09/audio_6b294070f5.mp3",
  },
  {
    id: 4,
    title: "Nature sounds.tropical,jungle,birds",
    src: "https://cdn.pixabay.com/audio/2022/03/26/audio_eab0c1eb43.mp3",
  },
  {
    id: 5,
    title: "Calm River Ambience | Loop",
    src: "https://cdn.pixabay.com/audio/2022/11/05/audio_a90e44eb25.mp3",
  },
];

export const Projects = {
  "1": {
    id: 1,
    name: "Aqua Note",
    description: "Note Taking app",
    tags: ["Next JS", "Typescript", "React", "Tailwind CSS"],
    image: "https://picsum.photos/100/100",
    previewLink: "",
    completed: false,
  },
  "2": {
    id: 2,
    name: "Just Transform",
    description: "Transforming shapes with CSS",
    tags: ["Next JS", "Typescript", "React", "Tailwind CSS"],
    image: "https://picsum.photos/100/100",
    previewLink: "",
    completed: false,
  },
  "3": {
    id: 3,
    name: "Canvas",
    description: "Canvas drawing app",
    tags: ["Next JS", "Typescript", "React", "Tailwind CSS"],
    image: "https://picsum.photos/100/100",
    previewLink: "",
    completed: false,
  },
  "4": {
    id: 4,
    name: "Name Search",
    description: "Search names by alphabet just by hovering over it",
    tags: ["Next JS", "Typescript", "React", "Tailwind CSS"],
    image: "https://picsum.photos/100/100",
    previewLink: "",
    completed: false,
  },
  5: {
    id: 5,
    name: "Slide Show",
    description: "View your Awesome moments Photos",
    tags: ["Next JS", "Typescript", "React", "Tailwind CSS"],
    image: "https://picsum.photos/100/100",
    previewLink: "",
    completed: true,
  },
};
